"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 00:38:26.014155

Migration rules (see docs/operations.md):
* Expand/contract only. Never drop or rename a column in the same release as the
  code that stops using it.
* Every new tenant table needs RLS: call enable_rls("<table>") in upgrade().
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- Row-level security ------------------------------------------------------
# Frozen copy of the policy SQL (migrations must not import app code that may change).
_ORG_FILTER = (
    "current_setting('app.system', true) = 'on' "
    "OR {col} = NULLIF(current_setting('app.org_id', true), '')::uuid"
)

TENANT_TABLES = [
    "memberships", "invites", "projects", "api_keys", "provider_keys", "traces", "spans",
    "datasets", "dataset_items", "candidates", "judges", "experiments", "experiment_runs",
    "judge_results", "human_labels", "judge_calibrations", "audit_log", "usage_counters",
]


def enable_rls(table: str, column: str = "org_id") -> None:
    cond = _ORG_FILTER.format(col=column)
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    # FORCE: the table owner (our app role) is subject to the policy too.
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(f"CREATE POLICY tenant_isolation ON {table} USING ({cond}) WITH CHECK ({cond})")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_state',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_cron_state'))
    )
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('personal', sa.Boolean(), nullable=False),
    sa.Column('quota_traces_per_day', sa.BigInteger(), nullable=False),
    sa.Column('quota_replay_runs_per_day', sa.BigInteger(), nullable=False),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs')),
    sa.UniqueConstraint('slug', name=op.f('uq_orgs_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('github_login', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('github_id', name=op.f('uq_users_github_id'))
    )
    op.create_index(op.f('ix_users_github_login'), 'users', ['github_login'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_login', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invites_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_invites_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('org_id', 'github_login', name=op.f('uq_invites_org_id_github_login'))
    )
    op.create_index('ix_invites_github_login', 'invites', ['github_login'], unique=False)
    op.create_index(op.f('ix_invites_org_id'), 'invites', ['org_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('max_attempts', sa.BigInteger(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_jobs_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_jobs_dedupe_key'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['priority', 'run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_memberships_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('org_id', 'user_id', name=op.f('uq_memberships_org_id_user_id'))
    )
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('retention_days', sa.BigInteger(), nullable=False),
    sa.Column('redaction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_projects_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('org_id', 'slug', name=op.f('uq_projects_org_id_slug'))
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('provider_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('last4', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_provider_keys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_provider_keys_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_keys'))
    )
    op.create_index(op.f('ix_provider_keys_org_id'), 'provider_keys', ['org_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('active_org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['active_org_id'], ['orgs.id'], name=op.f('fk_sessions_active_org_id_orgs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_usage_counters_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_counters')),
    sa.UniqueConstraint('org_id', 'day', 'metric', name=op.f('uq_usage_counters_org_id_day_metric'))
    )
    op.create_index(op.f('ix_usage_counters_org_id'), 'usage_counters', ['org_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_api_keys_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_keys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_api_keys_prefix'))
    )
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_candidates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_candidates_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_candidates_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_org_id'), 'candidates', ['org_id'], unique=False)
    op.create_index(op.f('ix_candidates_project_id'), 'candidates', ['project_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_size', sa.BigInteger(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('item_count', sa.BigInteger(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datasets_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_datasets_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_datasets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index(op.f('ix_datasets_org_id'), 'datasets', ['org_id'], unique=False)
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_table('judges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('rubric', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_reference', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_judges_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_judges_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_judges_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judges')),
    sa.UniqueConstraint('family_id', 'version', name=op.f('uq_judges_family_id_version'))
    )
    op.create_index(op.f('ix_judges_family_id'), 'judges', ['family_id'], unique=False)
    op.create_index(op.f('ix_judges_org_id'), 'judges', ['org_id'], unique=False)
    op.create_index(op.f('ix_judges_project_id'), 'judges', ['project_id'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('span_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.Column('llm_call_count', sa.BigInteger(), nullable=False),
    sa.Column('tool_call_count', sa.BigInteger(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('input_preview', sa.String(length=600), nullable=True),
    sa.Column('output_preview', sa.String(length=600), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_traces_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_traces_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traces')),
    sa.UniqueConstraint('project_id', 'external_id', name=op.f('uq_traces_project_id_external_id'))
    )
    op.create_index(op.f('ix_traces_org_id'), 'traces', ['org_id'], unique=False)
    op.create_index('ix_traces_project_created', 'traces', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_traces_project_start', 'traces', ['project_id', sa.literal_column('start_time DESC')], unique=False)
    op.create_index('ix_traces_tags', 'traces', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_api_key_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['api_keys.id'], name=op.f('fk_audit_log_actor_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_audit_log_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_index('ix_audit_org_created', 'audit_log', ['org_id', 'created_at'], unique=False)
    op.create_table('dataset_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=False),
    sa.Column('source_trace_id', sa.UUID(), nullable=True),
    sa.Column('source_external_id', sa.String(length=128), nullable=True),
    sa.Column('recording', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recording_ref', sa.String(length=500), nullable=True),
    sa.Column('slices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_preview', sa.String(length=600), nullable=True),
    sa.Column('llm_steps', sa.BigInteger(), nullable=False),
    sa.Column('tool_events', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_items_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_dataset_items_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_trace_id'], ['traces.id'], name=op.f('fk_dataset_items_source_trace_id_traces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_items')),
    sa.UniqueConstraint('dataset_id', 'position', name=op.f('uq_dataset_items_dataset_id_position'))
    )
    op.create_index('ix_dataset_items_dataset', 'dataset_items', ['dataset_id', 'position'], unique=False)
    op.create_index(op.f('ix_dataset_items_org_id'), 'dataset_items', ['org_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('baseline_candidate_id', sa.UUID(), nullable=True),
    sa.Column('baseline_mode', sa.String(length=20), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('repeats', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_items', sa.BigInteger(), nullable=False),
    sa.Column('done_items', sa.BigInteger(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ci', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_candidate_id'], ['candidates.id'], name=op.f('fk_experiments_baseline_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_experiments_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_experiments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_experiments_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_experiments_judge_id_judges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_experiments_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_experiments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_org_id'), 'experiments', ['org_id'], unique=False)
    op.create_index('ix_experiments_project_created', 'experiments', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)
    op.create_table('judge_calibrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=False),
    sa.Column('n', sa.BigInteger(), nullable=False),
    sa.Column('kappa', sa.Float(), nullable=True),
    sa.Column('kappa_low', sa.Float(), nullable=True),
    sa.Column('kappa_high', sa.Float(), nullable=True),
    sa.Column('raw_agreement', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_judge_calibrations_judge_id_judges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_judge_calibrations_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judge_calibrations'))
    )
    op.create_index(op.f('ix_judge_calibrations_judge_id'), 'judge_calibrations', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judge_calibrations_org_id'), 'judge_calibrations', ['org_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('trace_pk', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_ref', sa.String(length=500), nullable=True),
    sa.Column('output_ref', sa.String(length=500), nullable=True),
    sa.Column('input_bytes', sa.BigInteger(), nullable=False),
    sa.Column('output_bytes', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_spans_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_spans_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_pk'], ['traces.id'], name=op.f('fk_spans_trace_pk_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spans')),
    sa.UniqueConstraint('trace_pk', 'span_id', name=op.f('uq_spans_trace_pk_span_id'))
    )
    op.create_index(op.f('ix_spans_org_id'), 'spans', ['org_id'], unique=False)
    op.create_index('ix_spans_trace_start', 'spans', ['trace_pk', 'start_time'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('dataset_item_id', sa.UUID(), nullable=False),
    sa.Column('arm', sa.String(length=20), nullable=False),
    sa.Column('repeat_index', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('divergence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], name=op.f('fk_experiment_runs_dataset_item_id_dataset_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_runs_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_experiment_runs_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_runs')),
    sa.UniqueConstraint('experiment_id', 'dataset_item_id', 'arm', 'repeat_index', name=op.f('uq_experiment_runs_experiment_id_dataset_item_id_arm_repeat_index'))
    )
    op.create_index(op.f('ix_experiment_runs_org_id'), 'experiment_runs', ['org_id'], unique=False)
    op.create_index('ix_runs_experiment_status', 'experiment_runs', ['experiment_id', 'status'], unique=False)
    op.create_table('judge_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('dataset_item_id', sa.UUID(), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=False),
    sa.Column('repeat_index', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('arm', sa.String(length=20), nullable=True),
    sa.Column('order', sa.String(length=4), nullable=True),
    sa.Column('raw_choice', sa.String(length=8), nullable=True),
    sa.Column('winner', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('normalized', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], name=op.f('fk_judge_results_dataset_item_id_dataset_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_judge_results_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_judge_results_judge_id_judges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_judge_results_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_judge_results_run_id_experiment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judge_results'))
    )
    op.create_index('ix_judge_results_experiment', 'judge_results', ['experiment_id', 'dataset_item_id'], unique=False)
    op.create_index(op.f('ix_judge_results_judge_id'), 'judge_results', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judge_results_org_id'), 'judge_results', ['org_id'], unique=False)
    op.create_table('human_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judge_result_id', sa.UUID(), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_human_labels_judge_id_judges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_result_id'], ['judge_results.id'], name=op.f('fk_human_labels_judge_result_id_judge_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_human_labels_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_human_labels_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_labels')),
    sa.UniqueConstraint('judge_result_id', 'user_id', name=op.f('uq_human_labels_judge_result_id_user_id'))
    )
    op.create_index(op.f('ix_human_labels_judge_id'), 'human_labels', ['judge_id'], unique=False)
    op.create_index(op.f('ix_human_labels_org_id'), 'human_labels', ['org_id'], unique=False)
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        enable_rls(table)
    enable_rls("orgs", column="id")
    # Jobs: org-owned jobs are visible to their org; system jobs (org_id NULL) only to workers.
    enable_rls("jobs")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_labels_org_id'), table_name='human_labels')
    op.drop_index(op.f('ix_human_labels_judge_id'), table_name='human_labels')
    op.drop_table('human_labels')
    op.drop_index(op.f('ix_judge_results_org_id'), table_name='judge_results')
    op.drop_index(op.f('ix_judge_results_judge_id'), table_name='judge_results')
    op.drop_index('ix_judge_results_experiment', table_name='judge_results')
    op.drop_table('judge_results')
    op.drop_index('ix_runs_experiment_status', table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_org_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index('ix_spans_trace_start', table_name='spans')
    op.drop_index(op.f('ix_spans_org_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_judge_calibrations_org_id'), table_name='judge_calibrations')
    op.drop_index(op.f('ix_judge_calibrations_judge_id'), table_name='judge_calibrations')
    op.drop_table('judge_calibrations')
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_index('ix_experiments_project_created', table_name='experiments')
    op.drop_index(op.f('ix_experiments_org_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_dataset_items_org_id'), table_name='dataset_items')
    op.drop_index('ix_dataset_items_dataset', table_name='dataset_items')
    op.drop_table('dataset_items')
    op.drop_index('ix_audit_org_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_traces_tags', table_name='traces', postgresql_using='gin')
    op.drop_index('ix_traces_project_start', table_name='traces')
    op.drop_index('ix_traces_project_created', table_name='traces')
    op.drop_index(op.f('ix_traces_org_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_judges_project_id'), table_name='judges')
    op.drop_index(op.f('ix_judges_org_id'), table_name='judges')
    op.drop_index(op.f('ix_judges_family_id'), table_name='judges')
    op.drop_table('judges')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_org_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_candidates_project_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_org_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_usage_counters_org_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_provider_keys_org_id'), table_name='provider_keys')
    op.drop_table('provider_keys')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('jobs')
    op.drop_index(op.f('ix_invites_org_id'), table_name='invites')
    op.drop_index('ix_invites_github_login', table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_users_github_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('orgs')
    op.drop_table('cron_state')
    # ### end Alembic commands ###
